Parameters:
  UNAME:
    Description: "DB Username"
    Type: String

  PASS:
    Description: "DB Password"
    Type: String

Resources:
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "5"
      DBInstanceClass: db.t2.small
      Engine: MySQL
      MasterUsername: !Ref UNAME
      MasterUserPassword: !Ref PASS
      VPCSecurityGroups:
        - Fn::GetAtt: [ RDSSecurityGroup, GroupId ]
    DeletionPolicy: Snapshot

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: RDS_MYSQL
      GroupDescription: Allow Public MySQL Access

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "3306"
          ToPort: "3306"
          CidrIp: 0.0.0.0/0


Outputs:
    DBENDPOINT:
        Description: Name of the S3 bucket
        Value: !GetAtt  MyDB.Endpoint.Address