Parameters:
    BucketVersioningConfiguration:
        Description: Bucket versioning
        Type: String
    

Resources:
    S3Bucket:
        Type: "AWS::S3::Bucket"
        Properties:
            AccessControl: PublicRead
            PublicAccessBlockConfiguration:
                BlockPublicAcls: false
                BlockPublicPolicy: false
                IgnorePublicAcls: false
                RestrictPublicBuckets: false
            VersioningConfiguration:
                Status: !Ref BucketVersioningConfiguration
            Tags:
                - Key: Name
                  Value: Lambda

    PublicBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref S3Bucket

            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    Effect: Allow
                    Action:
                        - "s3:GetObject"
                    Resource:
                        - !Join ["/", [!GetAtt [S3Bucket, Arn], "*"]]
                    Principal: "*"

Outputs:
    S3BucketName:
        Description: Name of the S3 bucket
        Value: !Ref S3Bucket
